### PR TITLE
Add initial version.

### PR DESCRIPTION
**Pull request by JanJaguschQC**

### CODE REVIEW

**Comment by jonashaag** [comment]
Great! Why have a non-fixing version? We don't have it for the other hooks IIRC.

**Comment by JanJaguschQC** [comment]
> Great! Why have a non-fixing version? We don't have it for the other hooks IIRC.

Apparently, the repo where this hook would be used requires a non-fixing version: https://github.com/Quantco/barmer_drg_scoring_analytics/pull/1711/files

**Comment by borchero** [comment]
@JanJaguschQC thanks for taking the initiative to create this repository! We've been using a non-fixing version since most issues require manual intervention anyway. I think we get the same behavior when using the fixing hook, i.e. I guess you can just remove the linting hook .

**Comment by JanJaguschQC** [comment]
> @JanJaguschQC thanks for taking the initiative to create this repository! 🚀
> 
> We've been using a non-fixing version since most issues require manual intervention anyway. I think we get the same behavior when using the fixing hook, i.e. I guess you can just remove the linting hook .

Thanks @borchero! I've released a `1.2.1` tag which you should be able to use in your pre-commit config.

**Comment by borchero** [comment]
@JanJaguschQC awesome, thanks!

**Pull request merged**
